homeassistant:
  name: CASA
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  
  unit_system: metric
  time_zone: Europe/Rome
  
  customize: !include customize.yaml

# Enables the frontend
frontend:
panel_iframe:
  router:
    title: 'TP-LINK Router'
    icon: 'mdi:router-wireless'
    url: 'http://gio78.duckdns.org'

http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  ip_ban_enabled: True
  login_attempts_threshold: 3

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:
  include:
    domains:
      - sensor
      - binary_sensor
      - switch
      - climate
  exclude:
    entities:
      - group.temperature
      - sensor.greenwave_powernode_6_port_previous_reading_5_1
      - sensor.greenwave_powernode_6_port_previous_reading_5_1_2
      - sensor.greenwave_powernode_6_port_previous_reading_5_1_3
      - sensor.greenwave_powernode_6_port_previous_reading_5_1_4
      - sensor.greenwave_powernode_6_port_previous_reading_5_1_5
      - sensor.greenwave_powernode_6_port_previous_reading_5_1_6
      - sensor.greenwave_powernode_6_port_previous_reading_5_9
      - sensor.greenwave_powernode_6_port_previous_reading_5_9_2
      - sensor.greenwave_powernode_6_port_previous_reading_5_9_3
      - sensor.greenwave_powernode_6_port_previous_reading_5_9_4
      - sensor.greenwave_powernode_6_port_previous_reading_5_9_5
      - sensor.greenwave_powernode_6_port_previous_reading_5_9_6
      - sensor.fibaro_system_fgms001_motion_sensor_general_3_0
      - sensor.fibaro_system_fgms001_motion_sensor_general_4_0
      - sensor.pws_feelslike_c
      - sensor.pws_wind_kph
      - sensor.pws_wind_dir
      - sensor.pws_relative_humidity
      - sensor.pws_precip_today_metric
      - sensor.pws_location
      - sensor.pws_observation_time

# View all events in a logbook
logbook:
  include:
    domains:
      - sensor
      - binary_sensor
      - switch
      - climate
  exclude:
    entities:
      - group.temperature
      - group.prese
      - group.energia
      - group.potenza
      - group.meteo
      - group.info
      - sensor.fibaro_system_fgms001_motion_sensor_general_3_0
      - sensor.fibaro_system_fgms001_motion_sensor_general_4_0
      - sensor.pws_feelslike_c
      - sensor.pws_wind_kph
      - sensor.pws_wind_dir
      - sensor.pws_relative_humidity
      - sensor.pws_precip_today_metric
      - sensor.pws_location
      - sensor.pws_observation_time

# Track the sun
sun:


# Text to speech
tts:
  platform: google


mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: pi
  password: !secret mqtt_password

# TERMOSTATO NETATMO
netatmo:
  api_key: !secret netatmo_thermostat_api_key
  secret_key: !secret netatmo_thermostat_secret_key
  username: gio78ct@gmail.com
  password: !secret netatmo_thermostat_password

# Z-WAVE
zwave:
# config_path: /usr/local/lib/python3.4/dist-packages/libopenzwave-0.3.1-py3.4-linux-armv6l.egg/config
  config_path: /srv/homeassistant/homeassistant_venv/src/python-openzwave/openzwave/config
  usb_path: /dev/ttyAMA0
  polling_interval: 60000
  debug:
  #customize:
  #sensor.greenwave_powernode_6_port_energy_10:
  #polling_intensity: 1

# LG TV 47 pollici Salone
media_player:
  - platform: lg_netcast
    host: 192.168.1.47
    access_token: !secret tvlg_salone_token
    
    
#######################################
# NOTIFICATION ########################
#######################################
notify:
  - platform: telegram
    name: telegram
    chat_id: 300989693

  - name: google push
    platform: html5
    gcm_api_key: 'AAAAH2dh4rY:APA91bFoCZ8m6vt5WnvLo0Ndd9-oWzGiDMHGTrb3mjV3pqpgXPSbBM4Bp3CQT9-BLIhFz9tNm-J_beG4IeeKsW28KnB-bcQvooGGarF6Qi70yXGJNBauf-RPSeMX30QgucyiHyHbAHF5'
    gcm_sender_id: '134878454454'


telegram_bot:
  platform: polling
  api_key: 223675455:AAFN4hBtvOjPAbVI7h5fUlYXfhgvFipdbII
  allowed_chat_ids:
    - 300989693

########################################
# INCLUDES #############################
########################################
camera: !include_dir_list cameras/
automation: !include automation.yaml
group: !include groups.yaml
sensor: !include_dir_list sensors/
device_tracker: !include device_trackers.yaml
scene: !include scenes.yaml
# secret: !include secrets.yaml
zone: !include_dir_list zones/
