homeassistant:
  name: CASA
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation

  unit_system: metric
  time_zone: Europe/Rome
  customize: !include customize.yaml


http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  ip_ban_enabled: True
  login_attempts_threshold: 3

duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_access_token

frontend:
config:
updater:
conversation:
sun:
discovery:



# Text to speech
tts:
  - platform: google
  - platform: picotts
    language: 'it-IT'

# MQTT CLOUDMQTT ####################
#mqtt:
#  broker: m20.cloudmqtt.com
#  port: 10540
#  client_id: home-assistant-1
#  username: ha
#  password: !secret mqtt_password
#  keepalive: 60

# MQTT mosquitto ####################
mqtt:
  broker: 192.168.1.10
  port: 1883
  client_id: home-assistant-mosquitto-1
  username: !secret mqtt_username
  password: !secret mqtt_password

# Z-WAVE
zwave:
  usb_path: /dev/ttyAMA0
  config_path: /srv/homeassistant/src/python-openzwave/openzwave/config
  polling_interval: 30000

# TERMOSTATO NETATMO
netatmo:
  api_key: !secret netatmo_thermostat_api_key
  secret_key: !secret netatmo_thermostat_secret_key
  username: gio78ct@gmail.com
  password: !secret netatmo_thermostat_password 
  discovery: False

climate:
  platform: netatmo
#  relay: netatmo_relay
#  thermostat:
#    - Termostato Netatmo


# IP CAMERA
camera:
  - platform: mjpeg
    mjpeg_url: !secret wansview_camera_mjpeg_url
    username: admin
    password: !secret wansview_camera_password
    authentication: digest

# USB CAMERA
  - platform: local_file
    name: MS LifeCam HD-3000
    file_path: /tmp/lastsnap.jpg

# USB CAMERA 2
  - platform: mjpeg
    mjpeg_url: http://localhost:8081
    name: USB Camera

# LG TV 47 pollici Salone
#media_player:
#  - platform: lg_netcast
#    host: 192.168.1.47
#    access_token: 278540
#    name: "TV Salone"
#  - platform: squeezebox
#    host: 192.168.1.9
#    port: 9000
#    username:
#    password:

#######################################
# NOTIFICATION ########################
#######################################
notify:
#  - platform: telegram
#    name: telegram
#    chat_id: 300989693

  - name: google push
    platform: html5
    gcm_api_key: 'AAAAH2dh4rY:APA91bFoCZ8m6vt5WnvLo0Ndd9-oWzGiDMHGTrb3mjV3pqpgXPSbBM4Bp3CQT9-BLIhFz9tNm-J_beG4IeeKsW28KnB-bcQvooGGarF6Qi70yXGJNBauf-RPSeMX30QgucyiHyHbAHF5'
    gcm_sender_id: '134878454454'


#telegram_bot:
#  platform: polling
#  api_key: 223675455:AAFN4hBtvOjPAbVI7h5fUlYXfhgvFipdbII
#  allowed_chat_ids:
#    - 300989693

#################################################################
## AUTOMATIONS
#################################################################


#################################################################
# SCRIPTS #######################################################
#################################################################



########################################
# INCLUDES #############################
########################################
#automation: !include_dir_merge_list automation/
automation: !include automations.yaml
binary_sensor: !include binary_sensors.yaml
# camera: !include_dir_list cameras/
device_tracker: !include device_trackers.yaml
group: !include groups.yaml
input_boolean: !include misc/input_boolean.yaml
input_number: !include misc/input_number.yaml
# input_select: !include misc/input_select.yaml
# scene: !include scenes.yaml
#script: !include scripts.yaml
script: !include_dir_merge_list scripts/
#sensor: !include_dir_list sensors/
sensor: !include_dir_merge_list sensors/
shell_command: !include_dir_merge_named shell_command
switch: !include switches.yaml
#weather: !include_dir_list weather/
zone: !include_dir_merge_list zones/
logbook: !include logbook.yaml
history: !include history.yaml
